name: Build Wheels

on: [push, release]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:  [macos-14]
        python: ["3.12"]

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install "pybind11[global]"  # Install pybind11 with global flag
          pip install cibuildwheel
          
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.16.2
        env:
          CIBW_BUILD_VERBOSITY: 1
          # Optional: Skip 32-bit builds
          CIBW_SKIP: "*-win32 *-manylinux_i686"
          
      - name: Upload wheels
        uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
