name: Build Wheels

on: 
  workflow_dispatch: # only manual triggers

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:  [macos-latest]
        python: ["3.9"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: ${{ matrix.python }}
          channels: defaults
          activate-environment: build-env
          auto-activate-base: false

      - name: Install dependencies
        shell: bash -l {0}
        run: |
          conda install pybind11 cmake pip
          pip install cibuildwheel

      - name: Build wheels
          shell: bash -l {0}
          run: |
            echo "Python version: ${{ matrix.python }}"
            echo "First digit: ${{ matrix.python[0] }}"
            echo "Third digit: ${{ matrix.python[2] }}"
            echo "CIBW_BUILD pattern: cp${{ format('{0}{1}', matrix.python[0], matrix.python[2]) }}-*"
            python -m cibuildwheel
    env:
      CIBW_BUILD_VERBOSITY: 1
      CIBW_SKIP: "*-win32 *-manylinux_i686 pp*"
      CIBW_BUILD: "cp${{ format('{0}{1}', matrix.python[0], matrix.python[2]) }}-*"

      - name: Store the wheels
        uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}-${{ matrix.python }}
          path: ./wheelhouse/*.whl
          compression-level: 0

  # publish-to-testpypi:
  #   needs: build_wheels
  #   runs-on: ubuntu-latest
  #   environment:
  #     name: testpypi
  #     url: https://test.pypi.org/project/pyember/
  #   permissions:
  #     id-token: write
  #
  #   steps:
  #     - name: Download all wheels
  #       uses: actions/download-artifact@v4
  #       with:
  #         pattern: wheels-*  # Download wheels from all OS builds
  #         path: dist/
  #         merge-multiple: true  # Merge all wheels into dist directory
  #        
  #     - name: Publish wheels to TestPyPI
  #       uses: pypa/gh-action-pypi-publish@release/v1
  #       with:
  #         repository-url: https://test.pypi.org/legacy/
