name: Build Wheels

on: [push, release]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:  [macos-14]
        python: ["3.12"]

    steps:
      - uses: actions/checkout@v4
      - uses: pypa/cibuildwheel@v2.16.2
