name: publish-testpypi 
on: 
  workflow_run: 
    workflows: ["build-wheels-macos-arm64", "build-wheels-win-amd64"]
    types: 
      - completed
    branches: [main]
jobs:
  verify-artifacts:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Download macOS artifacts
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build-wheels-macos-arm64
          workflow_conclusion: success
          path: dist/macos/
          skip_unpack: false

      - name: Download Windows artifacts
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build-wheels-win-amd64
          workflow_conclusion: success
          path: dist/windows/
          skip_unpack: false

      - name: Organize all wheels
        run: |
          mkdir -p dist/final
          # Move macOS wheels
          find dist/macos -name "*.whl" -exec mv {} dist/final/ \;
          # Move Windows wheels
          find dist/windows -name "*.whl" -exec mv {} dist/final/ \;
          echo "Contents of dist/final:"
          ls -la dist/final/

  publish-to-testpypi:
    needs: verify-artifacts
    runs-on: ubuntu-latest
    environment:
      name: testpypi
      url: https://test.pypi.org/project/pyember/
    permissions:
      id-token: write
  
    steps:
      - name: Download macOS artifacts
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build-wheels-macos-arm64
          workflow_conclusion: success
          path: dist/macos/
          skip_unpack: false

      - name: Download Windows artifacts
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build-wheels-win-amd64
          workflow_conclusion: success
          path: dist/windows/
          skip_unpack: false

      - name: Clean and organize wheels
        run: |
          # Create directories
          mkdir -p dist/final
          
          # Move all wheels to final directory
          find dist/macos dist/windows -name "*.whl" -exec mv {} dist/final/ \;
          
          # Clean up and reorganize
          mv dist/final/* dist/
          rm -rf dist/final dist/macos dist/windows
          
          echo "Final contents of dist directory:"
          ls -la dist/
        
      - name: Publish wheels to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          verbose: true
