name: publish-testpypi 
on:
  workflow_call: 

jobs:
  publish-to-testpypi:
    runs-on: ubuntu-latest
    environment:
      name: testpypi
      url: https://test.pypi.org/project/pyember/
    permissions:
      id-token: write
  
    steps:
      - name: Download macOS artifacts
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build-wheels-macos-arm64
          name: macos-wheels-*
          workflow_conclusion: success
          path: dist/macos/
          skip_unpack: false

      - name: Download Windows artifacts
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build-wheels-win-amd64
          name: windows-wheels-*
          workflow_conclusion: success
          path: dist/windows/
          skip_unpack: false

      - name: Clean and organize wheels
        run: |
          # Create directories
          mkdir -p dist/final
          
          # Move all wheels to final directory
          find dist/macos dist/windows -name "*.whl" -exec mv {} dist/final/ \;
          
          # Clean up and reorganize
          mv dist/final/* dist/
          rm -rf dist/final dist/macos dist/windows
          
          echo "Final contents of dist directory:"
          ls -la dist/
        
      - name: Publish wheels to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          verbose: true
