name: publish-testpypi 
on: 
  workflow_run: 
    workflows: ["build-wheels-win-amd64"]
    types: 
      - completed
    branches: [main]

permissions:
  id-token: write

jobs:
  verify-artifacts:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Download macOS artifacts
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build-wheels-macos-arm64
          name: macos-wheels-macos-latest-3
          name_is_regexp: true
          workflow_conclusion: success
          path: dist/
          skip_unpack: false
          
      - name: Download Windows artifacts
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build-wheels-win-amd64
          name: windows-wheels-windows-latest-3
          name_is_regexp: true
          workflow_conclusion: success
          path: dist/
          skip_unpack: false

      - name: List downloaded files
        run: |
          echo "Contents of dist directory before organizing:"
          ls -R dist/
          
      - name: Organize all wheels
        run: |
          mkdir -p dist/final
          find dist -name "*.whl" -exec mv {} dist/final/ \;
          echo "Contents of dist/final:"
          ls -la dist/final/
          
      - name: Upload organized wheels
        uses: actions/upload-artifact@v4
        with:
          name: organized-wheels
          path: dist/final/*.whl
          
  publish-to-testpypi:
    needs: verify-artifacts
    runs-on: ubuntu-latest
    environment:
      name: testpypi
      url: https://test.pypi.org/project/pyember/
    permissions:
      id-token: write
  
    steps:
      - name: Download organized wheels
        uses: actions/download-artifact@v4
        with:
          name: organized-wheels
          path: dist/
          
      - name: List files to publish
        run: |
          echo "Contents of dist directory:"
          ls -la dist/
        
      - name: Publish wheels to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          verbose: true
